Add bookings
M0L0D0Y/java-shareit pull request #3
Opened 2022-08-31 11:46 UTC by M0L0D0Y

2022-09-01 13:29 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String HEADER_USER_ID = "X-Sharer-User-Id";
константы и другие поля стоит разделить пустой строкой

2022-09-01 13:30 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +
достаточно одной пустой строки

2022-09-01 13:30 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Booking replyFromOwner(long userId, long bookingId, boolean approved);
по названию трудно понять, что делает сервис
может лучше `confirmBookingByOwner` ?

2022-09-01 13:31 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<Booking> getBookingsBooker(long userId, String state);
тут тоже стоит назвать более понятно
`getBookingsByBookerId`

2022-09-01 13:32 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<Booking> getBookingsOwner(long userId, String state);
`getBookingsByOwnerId`

2022-09-01 13:34 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new UnsupportedStatusException("Неподдерживаемый статус");
стоит добавить в сообщение это невалидное значение

2022-09-01 13:37 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                        List<Booking> allBookings = bookingStorage.findByItemId(item.getId());
не очень хорошо, когда на каждый отдельный итем осуществляется поход в базу за данными, лучше сделать сразу один поход для всех items

это не критично в учебных проектах с in memory хранилищем, но в реальном проекте такое может привести к более долгим ответам сервиса и большой нагрузкой на бд

2022-09-01 13:39 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/NextBooking.java
> +public class NextBooking {
действительно ли нужны два разных класса LastBooking и NextBooking, хранящих одни и те же данные?

2022-09-01 13:40 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public BookingMapper(ItemService itemService,
можно заменить аннотацией из lombok

2022-09-01 13:42 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private static final byte MIN_SIZE = 1;
константы и другие поля стоит разделить пустой строкой

2022-09-01 13:45 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private static final byte FIRST_ELEMENT = 0;
стоит улучшить названия констант, чтобы было более понятно, что они хранят
например
`FIRST_BOOKING_INDEX`
`MIN_BOOKING_AMOUNT` (но эта константа может и не нужна, там по коду понятно, что если бронирований больше 1, то надо сортировать)

2022-09-01 13:47 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/OutputItemDtoWithComment.java
> +public class OutputItemDtoWithComment {
можно назвать `FullItemResponseDto`

2022-09-01 13:48 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/OutputItemDtoWithComment.java
> +public class OutputItemDtoWithComment {
но тогда и остальные дто стоит назвать в таком же стиле (вместо Input, Output)
`BookingRequestDto`, `BookingResponseDto` и тд

2022-09-01 13:49 UTC, makholin requested changes
Нужно исправить замечания

2022-09-02 07:42 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +
исправил

2022-09-02 07:44 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Booking replyFromOwner(long userId, long bookingId, boolean approved);
исправил

2022-09-02 07:44 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<Booking> getBookingsBooker(long userId, String state);
исправил

2022-09-02 07:45 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<Booking> getBookingsOwner(long userId, String state);
исправил

2022-09-02 07:47 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    List<Booking> findAllPastBookingsByItemId(long itemId, LocalDateTime dateTime);
исправил

2022-09-02 07:48 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new UnsupportedStatusException("Неподдерживаемый статус");
исправил

2022-09-02 07:49 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private static final byte MIN_SIZE = 1;
исправил

2022-09-02 07:51 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private static final byte FIRST_ELEMENT = 0;
исправил

2022-09-02 08:09 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/NextBooking.java
> +public class NextBooking {
исправил

2022-09-02 08:51 UTC, M0L0D0Y commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                        List<Booking> allBookings = bookingStorage.findByItemId(item.getId());
исправил

2022-09-04 12:50 UTC, makholin approved these changes
Работа принята

2022-09-06 13:45 UTC, merged